testrail:
  base_url: "https://tcgroup.testrail.io"
  username: "cplus.jack@gmail.com"
  password: "Aa123456!"

jira:
  base_url: "https://jira.tc-gaming.co/jira/"
  username: "jacky.h"
  password: "Abcd1234"

gsheet:
    credentials: "stwin-report-25ce8aecb2b7.json"
    qa_report_url: "https://docs.google.com/spreadsheets/d/1O7hrdmeHM_yiEm8-FghJ6MbRdQDRJgxQwRqdn44LmNA"

telegram:
    token: "7036134694:AAG7RTtJ7Cztew7iWtLJZnm0k_UalJLgkYE"
    group_id: "-4593454565"
    channel_id: "-1002396980679"